services:

  mongo:
    image: mongo:4.4.18-rc0-focal
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: shoppingify
      MONGO_INITDB_ROOT_PASSWORD: shoppingify
      MONGO_INITDB_DATABASE: shoppingifyDB
    volumes:
      - ./data:/etc/mongo
    ports:
      - 27017:27017
    command: [  --auth, --replSet=rs0, --dbpath=/data]
  
