services:

  mongo:
    image: mongo:4.4.18-rc0-focal
    restart: always
    env_file:
      - ./.env
    volumes:
      - ./data:/etc/mongo
    ports:
      - 27017:27017

  web:
    build: .
    image: shoppingify
    ports:
      - 3000:3000
    env_file:
      - ./.env
    depends_on:
      - mongo
